version: '3.5'

services:
  marvin-postgres-db:
    image: postgres
    restart: always
    container_name: marvin-postgres-db
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - postgres-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  atm-autenticador-api:
    image: noh4nsen/atm-autenticador-api:latest
    restart: always
    container_name: atm-autenticador-api
    environment:
      - ASPNETCORE_URLS=https://+443;http://+80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_HTTP_PORT=80
      - Kestrel__Certificates__Default__Path=${HTTPS_CERTIFICATE_PATH_AUTENTICADOR}
      - Kestrel__Certificates__Default__Password=${HTTPS_CERTIFICATE_PASSWORD}
    ports:
      - 5680:80
      - 5681:443
    depends_on:
      - marvin-postgres-db
    networks: 
      - postgres-net

  atm-clientes-api:
    image: noh4nsen/atm-clientes-api:latest
    restart: always
    container_name: atm-clientes-api
    environment:
      - ASPNETCORE_URLS=https://+443;http://+80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_HTTP_PORT=80
      - Kestrel__Certificates__Default__Path=${HTTPS_CERTIFICATE_PATH_CLIENTES}
      - Kestrel__Certificates__Default__Password=${HTTPS_CERTIFICATE_PASSWORD}
    ports:
      - 5676:80
      - 5677:443
    depends_on:
      - marvin-postgres-db
      - atm-autenticador-api
    networks: 
      - postgres-net

  atm-fornecedor-api:
    image: noh4nsen/atm-fornecedor-api:latest
    restart: always
    container_name: atm-fornecedor-api
    environment:
      - ASPNETCORE_URLS=https://+443;http://+80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_HTTP_PORT=80
      - Kestrel__Certificates__Default__Path=${HTTPS_CERTIFICATE_PATH_FORNECEDOR}
      - Kestrel__Certificates__Default__Password=${HTTPS_CERTIFICATE_PASSWORD}
    ports:
      - 5674:80
      - 5675:443
    depends_on:
      - marvin-postgres-db
      - atm-autenticador-api
    networks: 
      - postgres-net

  atm-atendimento-api:
    image: noh4nsen/atm-atendimento-api:latest
    restart: always
    container_name: atm-atendimento-api
    environment:
      - ASPNETCORE_URLS=https://+443;http://+80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_HTTP_PORT=80
      - Kestrel__Certificates__Default__Path=${HTTPS_CERTIFICATE_PATH_ATENDIMENTO}
      - Kestrel__Certificates__Default__Password=${HTTPS_CERTIFICATE_PASSWORD}
    ports:
      - 5678:80
      - 5679:443
    depends_on:
      - marvin-postgres-db
      - atm-autenticador-api
      - atm-clientes-api
      - atm-fornecedor-api
    networks: 
      - postgres-net

  atm-marvin-webapp:
    image: noh4nsen/atm-marvin-webapp:latest
    restart: always
    container_name: marvin
    ports:
      - 80:80  
    depends_on:
      - marvin-postgres-db
      - atm-autenticador-api
      - atm-clientes-api
      - atm-fornecedor-api
      - atm-atendimento-api
    networks: 
      - postgres-net

networks:
  postgres-net:
    driver: bridge
    external: true

volumes:
  postgres_data: