version: '3.5'

services:
  marvin-postgres-db:
    image: postgres
    restart: always
    container_name: marvin-postgres-db
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - postgres-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  postgres-net:
    driver: bridge
    external: true

volumes:
  postgres_data: